version: 0.2

phases:
  install:

  pre_build:
    commands:
      - echo No pre-build required

  build:
    commands:
      - echo Build started on `date`

  post_build:
    commands:
      - echo build completed `date`

artifacts:
  files:
    - build/**/*