version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn

  pre_build:
    commands:
      - yarn install

  build:
    commands:
      - echo Build started on `date`
      - yarn run build

  post_build:
    commands:
      - echo build completed `date`

artifacts:
  files:
    - build/**/*